# Generated by Django 5.0.2 on 2024-02-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_business",
            field=models.BooleanField(default=False),
        ),
    ]
